eureka :
  instance :
    prefer-ip-address : true
  client :
    register-with-eureka : true
    fetch-register : true
    service-url :
      defaultZone : ${EUREKA_SEVER_ADDRESS:http://localhost:8761/eureka/}
    instance :
      hostname : localhost


okta :
  oauth2 :
    issuer : https://dev-84506615.okta.com/oauth2/default
    audience : api://default
